# Generated by Django 5.1.3 on 2024-11-12 04:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShopOwners",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=15, unique=True)),
                ("owner_name", models.CharField(max_length=200)),
                ("password", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("shop_name", models.CharField(max_length=200)),
                ("shop_phone", models.CharField(max_length=15)),
                ("shop_address", models.TextField()),
            ],
        ),
    ]
