# Generated by Django 5.1.3 on 2024-11-12 06:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopowners",
            name="block",
            field=models.BooleanField(default=False),
        ),
    ]
