# Generated by Django 5.1.3 on 2024-11-16 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_apis", "0004_bookings_service_id"),
        ("user_app", "0004_sub_services"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booked_sub_services",
            name="booked_sub_services",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client_details",
                to="user_app.sub_services",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="clinet_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client_details",
                to="app_apis.clients",
            ),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="service_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_details",
                to="user_app.services",
            ),
        ),
    ]
