# Generated by Django 5.1.3 on 2024-11-16 11:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_apis", "0005_alter_booked_sub_services_booked_sub_services_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookings",
            old_name="clinet_id",
            new_name="client_id",
        ),
    ]
