# Generated by Django 5.1.3 on 2024-11-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_apis", "0008_bookings_ending_time_bookings_start_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client_requirements",
            name="img1",
            field=models.FileField(blank=True, null=True, upload_to="uploads/"),
        ),
        migrations.AlterField(
            model_name="client_requirements",
            name="img2",
            field=models.FileField(blank=True, null=True, upload_to="uploads/"),
        ),
        migrations.AlterField(
            model_name="client_requirements",
            name="img3",
            field=models.FileField(blank=True, null=True, upload_to="uploads/"),
        ),
        migrations.AlterField(
            model_name="client_requirements",
            name="img4",
            field=models.FileField(blank=True, null=True, upload_to="uploads/"),
        ),
    ]
