# Generated by Django 5.1.3 on 2024-11-18 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_apis", "0009_alter_client_requirements_img1_and_more"),
        ("user_app", "0004_sub_services"),
    ]

    operations = [
        migrations.AddField(
            model_name="clients",
            name="owner_name",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="user_app.shopowners",
            ),
            preserve_default=False,
        ),
    ]
