# Generated by Django 5.1.3 on 2024-11-18 17:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_apis", "0010_clients_owner_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookings",
            old_name="balance_amount",
            new_name="advance_amount",
        ),
    ]
