# Generated by Django 5.1.3 on 2024-11-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_apis", "0011_rename_balance_amount_bookings_advance_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="expenses",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="expenses",
            name="type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
